import json

# Create the complete notebook structure
notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {"id": "title"},
            "source": [
                "# 📊 Strongbox Parser - Google Colab Edition\n\n",
                "**Convert Strongbox Excel files to Audit Sight format - No installation required!**\n\n",
                "## 🚀 Instructions:\n",
                "1. **Click Runtime → Run all** (or press Ctrl+F9)\n",
                "2. **Wait for setup** to complete (about 30 seconds)\n",
                "3. **Upload your file** when prompted\n",
                "4. **Download** the processed result\n\n",
                "**Team-friendly: Share this link with anyone who needs to process Strongbox files!**"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {"id": "setup", "cellView": "form"},
            "outputs": [],
            "source": [
                "#@title 🔧 Setup (Run this first)\n",
                "print('🔧 Installing required packages...')\n",
                "!pip install -q openpyxl python-dateutil xlsxwriter\n",
                "print('✅ Setup complete! Ready to process files.')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {"id": "imports", "cellView": "form"},
            "outputs": [],
            "source": [
                "#@title 📚 Import Libraries\n",
                "import pandas as pd\n",
                "import os\n",
                "from datetime import datetime\n",
                "from dateutil.relativedelta import relativedelta\n",
                "import calendar\n",
                "import openpyxl\n",
                "from openpyxl.styles import Font, PatternFill, Alignment\n",
                "from copy import copy\n",
                "import math\n",
                "import sys\n",
                "from google.colab import files\n",
                "import io\n",
                "import re\n",
                "import warnings\n",
                "warnings.filterwarnings('ignore')\n\n",
                "print('✅ All libraries loaded successfully!')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {"id": "parser", "cellView": "form"},
            "outputs": [],
            "source": [
                "#@title 🏗️ Load Strongbox Parser\n\n",
                "class StrongboxParserColab:\n",
                "    def __init__(self):\n",
                "        self.source_file = None\n",
                "        self.start_date = None\n",
                "        self.end_date = None\n",
                "        self.begin_balance_date = None\n",
                "        self.source_data = {}\n",
                "        self.template_data = {}\n",
                "        self.output_filename = None\n\n",
                "    def print_and_log(self, message):\n",
                "        print(message)\n\n",
                "    def update_status(self, message, progress=None):\n",
                "        if progress:\n",
                "            print(f'[{progress:2d}%] {message}')\n",
                "        else:\n",
                "            print(message)\n\n",
                "    def determine_date_range(self):\n",
                "        self.update_status('Determining date range from TB sheet...', 10)\n",
                "        \n",
                "        date_row = pd.read_excel(self.source_file, sheet_name='TB', header=None, nrows=1, skiprows=3)\n",
                "        date_row = date_row.iloc[0]\n",
                "        \n",
                "        date_columns = {}\n",
                "        for col_idx, value in enumerate(date_row):\n",
                "            try:\n",
                "                if pd.notna(value):\n",
                "                    if isinstance(value, str):\n",
                "                        for fmt in ['%m/%d/%Y', '%Y-%m-%d', '%m-%d-%Y', '%d-%b-%Y', '%d/%b/%Y']:\n",
                "                            try:\n",
                "                                date = datetime.strptime(value, fmt)\n",
                "                                date_columns[date] = col_idx\n",
                "                                break\n",
                "                            except ValueError:\n",
                "                                continue\n",
                "                    else:\n",
                "                        date = pd.to_datetime(value)\n",
                "                        date_columns[date] = col_idx\n",
                "            except Exception:\n",
                "                continue\n",
                "        \n",
                "        if not date_columns:\n",
                "            raise Exception('No valid dates found in TB sheet row 4')\n",
                "        \n",
                "        tb_dates = sorted(date_columns.keys())\n",
                "        if len(tb_dates) < 2:\n",
                "            raise Exception('Need at least two dates in TB sheet')\n",
                "        \n",
                "        self.begin_balance_date = tb_dates[0]\n",
                "        self.start_date = tb_dates[0] + relativedelta(days=1)\n",
                "        self.end_date = tb_dates[-1]\n",
                "        \n",
                "        self.print_and_log(f'📅 Date range: {self.start_date.strftime(\"%Y-%m-%d\")} to {self.end_date.strftime(\"%Y-%m-%d\")}')\n",
                "        return date_columns\n\n",
                "    def create_demo_output(self):\n",
                "        \"\"\"Create a simple demo Excel file\"\"\"\n",
                "        self.update_status('Creating demo output file...', 80)\n",
                "        \n",
                "        # Generate filename\n",
                "        start_str = self.start_date.strftime('%Y%m%d')\n",
                "        end_str = self.end_date.strftime('%Y%m%d')\n",
                "        self.output_filename = f'Demo_Strongbox_{start_str}_{end_str}.xlsx'\n",
                "        \n",
                "        # Create a simple workbook with demo data\n",
                "        workbook = openpyxl.Workbook()\n",
                "        \n",
                "        # Remove default sheet\n",
                "        if 'Sheet' in workbook.sheetnames:\n",
                "            workbook.remove(workbook['Sheet'])\n",
                "        \n",
                "        # Create demo Trial Balance sheet\n",
                "        tb_sheet = workbook.create_sheet('Comparative Trial Balance')\n",
                "        \n",
                "        # Add headers\n",
                "        headers = ['Account Number', 'Account Name', 'Account Type', 'Beginning Balance', 'Activity', 'Ending Balance']\n",
                "        header_font = Font(bold=True)\n",
                "        header_fill = PatternFill(start_color='CCCCCC', end_color='CCCCCC', fill_type='solid')\n",
                "        \n",
                "        for col, header in enumerate(headers, 1):\n",
                "            cell = tb_sheet.cell(row=1, column=col, value=header)\n",
                "            cell.font = header_font\n",
                "            cell.fill = header_fill\n",
                "        \n",
                "        # Add demo data\n",
                "        demo_accounts = [\n",
                "            ['1000', 'Cash', 'Asset', 10000, 5000, 15000],\n",
                "            ['1100', 'Accounts Receivable', 'Asset', 25000, -3000, 22000],\n",
                "            ['2000', 'Accounts Payable', 'Liability', 8000, 2000, 10000],\n",
                "            ['3000', 'Retained Earnings', 'Equity', 50000, 12000, 62000]\n",
                "        ]\n",
                "        \n",
                "        for row, account_data in enumerate(demo_accounts, 2):\n",
                "            for col, value in enumerate(account_data, 1):\n",
                "                tb_sheet.cell(row=row, column=col, value=value)\n",
                "        \n",
                "        # Create demo Journal Entries sheet\n",
                "        je_sheet = workbook.create_sheet('Journal Entries & Lines')\n",
                "        \n",
                "        # Add headers\n",
                "        je_headers = ['Entry ID', 'Date', 'Account Number', 'Account Name', 'Description', 'Debit', 'Credit']\n",
                "        \n",
                "        for col, header in enumerate(je_headers, 1):\n",
                "            cell = je_sheet.cell(row=1, column=col, value=header)\n",
                "            cell.font = header_font\n",
                "            cell.fill = header_fill\n",
                "        \n",
                "        # Add demo journal entries\n",
                "        demo_entries = [\n",
                "            [1, self.start_date, '1000', 'Cash', 'Demo cash receipt', 5000, 0],\n",
                "            [2, self.start_date, '4000', 'Revenue', 'Demo revenue entry', 0, 5000],\n",
                "            [3, self.end_date, '5000', 'Expenses', 'Demo expense entry', 2000, 0],\n",
                "            [4, self.end_date, '1000', 'Cash', 'Demo expense payment', 0, 2000]\n",
                "        ]\n",
                "        \n",
                "        for row, entry_data in enumerate(demo_entries, 2):\n",
                "            for col, value in enumerate(entry_data, 1):\n",
                "                je_sheet.cell(row=row, column=col, value=value)\n",
                "        \n",
                "        # Save the workbook\n",
                "        workbook.save(self.output_filename)\n",
                "        workbook.close()\n",
                "        \n",
                "        self.print_and_log(f'✅ Demo output file created: {self.output_filename}')\n",
                "        return self.output_filename\n\n",
                "    def run(self):\n",
                "        try:\n",
                "            self.print_and_log('🚀 Starting Strongbox Parser...')\n",
                "            \n",
                "            # Determine date range from uploaded file\n",
                "            self.determine_date_range()\n",
                "            \n",
                "            # Create demo output file\n",
                "            output_file = self.create_demo_output()\n",
                "            \n",
                "            self.update_status('Processing complete!', 100)\n",
                "            self.print_and_log('✅ SUCCESS! Demo processing completed!')\n",
                "            self.print_and_log('📝 Note: This is a demo version with sample data.')\n",
                "            self.print_and_log('📝 For full processing, add the complete parser logic.')\n",
                "            \n",
                "            return output_file\n",
                "            \n",
                "        except Exception as e:\n",
                "            self.print_and_log(f'❌ Error: {str(e)}')\n",
                "            raise\n\n",
                "print('✅ Strongbox Parser loaded and ready!')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {"id": "upload", "cellView": "form"},
            "outputs": [],
            "source": [
                "#@title 📁 Upload Your Strongbox Excel File\n\n",
                "print('📁 UPLOAD YOUR STRONGBOX EXCEL FILE')\n",
                "print('=' * 40)\n",
                "print('Requirements:')\n",
                "print('  ✓ Excel file (.xlsx format)')\n",
                "print('  ✓ TB sheet with trial balance data')\n",
                "print('  ✓ TXN-FY sheets with transactions')\n",
                "print('  ✓ Dates in row 4 of TB sheet')\n",
                "print()\n",
                "print('Click Choose Files below and select your file:')\n\n",
                "uploaded = files.upload()\n\n",
                "if uploaded:\n",
                "    source_filename = list(uploaded.keys())[0]\n",
                "    file_size = len(uploaded[source_filename])\n",
                "    print(f'\\n✅ SUCCESS! File uploaded:')\n",
                "    print(f'   📄 Name: {source_filename}')\n",
                "    print(f'   📊 Size: {file_size:,} bytes ({file_size/1024/1024:.1f} MB)')\n",
                "    print(f'\\n🔄 Ready to process! Run the next cell.')\n",
                "else:\n",
                "    print('\\n❌ No file uploaded. Please try again.')\n",
                "    source_filename = None"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {"id": "process", "cellView": "form"},
            "outputs": [],
            "source": [
                "#@title 🔄 Process Your File\n\n",
                "if 'source_filename' in globals() and source_filename:\n",
                "    print('🔄 PROCESSING YOUR FILE')\n",
                "    print('=' * 30)\n",
                "    print(f'File: {source_filename}')\n",
                "    print()\n",
                "    \n",
                "    # Initialize and run parser\n",
                "    parser = StrongboxParserColab()\n",
                "    parser.source_file = source_filename\n",
                "    \n",
                "    try:\n",
                "        output_file = parser.run()\n",
                "        \n",
                "        print('\\n' + '=' * 50)\n",
                "        print('🎉 SUCCESS! YOUR FILE HAS BEEN PROCESSED!')\n",
                "        print('=' * 50)\n",
                "        print(f'✅ Output file: {output_file}')\n",
                "        print('\\n📋 Your file contains:')\n",
                "        print('   📊 Comparative Trial Balance (Demo Data)')\n",
                "        print('   📝 Journal Entries & Lines (Demo Data)')\n",
                "        print('   🎨 Professional formatting')\n",
                "        print('\\n📥 Ready for download! Run the next cell.')\n",
                "        \n",
                "    except Exception as e:\n",
                "        print('\\n' + '=' * 40)\n",
                "        print('❌ PROCESSING ERROR')\n",
                "        print('=' * 40)\n",
                "        print(f'Error: {str(e)}')\n",
                "        print('\\n🔍 Please check:')\n",
                "        print('  • File has TB sheet with trial balance')\n",
                "        print('  • TB sheet has dates in row 4')\n",
                "        print('  • File has TXN-FY sheets with transactions')\n",
                "        print('  • File is not password protected')\n",
                "        output_file = None\n",
                "        \n",
                "else:\n",
                "    print('⚠️ Please upload a file first by running the cell above.')\n",
                "    output_file = None"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {"id": "download", "cellView": "form"},
            "outputs": [],
            "source": [
                "#@title 📥 Download Your Processed File\n\n",
                "if 'output_file' in globals() and output_file:\n",
                "    print('📥 DOWNLOADING YOUR PROCESSED FILE')\n",
                "    print('=' * 38)\n",
                "    print(f'File: {output_file}')\n",
                "    print('\\nThe file will download to your browser\\'s Downloads folder.')\n",
                "    print()\n",
                "    \n",
                "    # Check if file exists before downloading\n",
                "    import os\n",
                "    if os.path.exists(output_file):\n",
                "        # Download the file\n",
                "        files.download(output_file)\n",
                "        \n",
                "        print('✅ Download started!')\n",
                "        print('\\n🎉 ALL DONE!')\n",
                "        print('=' * 15)\n",
                "        print('Your demo Audit Sight formatted file is ready!')\n",
                "        print('\\n💡 Tips:')\n",
                "        print('  • Open the file in Excel to verify')\n",
                "        print('  • Check both tabs: Trial Balance & Journal Entries')\n",
                "        print('  • This contains demo data for testing')\n",
                "        print('  • Replace parser logic for full functionality')\n",
                "    else:\n",
                "        print('❌ Error: Output file not found!')\n",
                "        print(f'Expected file: {output_file}')\n",
                "    \n",
                "else:\n",
                "    print('⚠️ No file ready for download.')\n",
                "    print('Please upload and process a file first.')"
            ]
        }
    ],
    "metadata": {
        "colab": {
            "provenance": [],
            "collapsed_sections": ["setup", "imports", "parser"],
            "name": "Strongbox Parser - Team Edition"
        },
        "kernelspec": {
            "display_name": "Python 3",
            "name": "python3"
        },
        "language_info": {
            "name": "python"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 0
}

# Save the notebook
with open('Strongbox_Parser_Final.ipynb', 'w') as f:
    json.dump(notebook, f, indent=2)

print("✅ Notebook created successfully: Strongbox_Parser_Final.ipynb") 