import json

# Create the complete notebook structure with FULL functionality
notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {"id": "title"},
            "source": [
                "# 📊 Strongbox Parser - Google Colab Edition\n\n",
                "**Convert Strongbox Excel files to Audit Sight format - No installation required!**\n\n",
                "## 🚀 Instructions:\n",
                "1. **Click Runtime → Run all** (or press Ctrl+F9)\n",
                "2. **Wait for setup** to complete (about 30 seconds)\n",
                "3. **Upload your file** when prompted\n",
                "4. **Download** the processed result\n\n",
                "**Features:**\n",
                "- ✅ Processes multiple TXN-FY sheets with real transaction data\n",
                "- ✅ Auto-detects date ranges from TB data\n",
                "- ✅ Creates Comparative Trial Balance from your accounts\n",
                "- ✅ Generates Journal Entries & Lines from your transactions\n",
                "- ✅ Professional Excel formatting\n",
                "- ✅ Data cleaning and Unicode handling\n",
                "- ✅ Complete with all required tabs (Instructions, Banking, etc.)\n\n",
                "**Team-friendly: Share this link with anyone who needs to process Strongbox files!**"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {"id": "setup", "cellView": "form"},
            "outputs": [],
            "source": [
                "#@title 🔧 Setup (Run this first)\n",
                "print('🔧 Installing required packages...')\n",
                "!pip install -q openpyxl python-dateutil xlsxwriter\n",
                "print('✅ Setup complete! Ready to process files.')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {"id": "imports", "cellView": "form"},
            "outputs": [],
            "source": [
                "#@title 📚 Import Libraries\n",
                "import pandas as pd\n",
                "import os\n",
                "from datetime import datetime\n",
                "from dateutil.relativedelta import relativedelta\n",
                "import calendar\n",
                "import openpyxl\n",
                "from openpyxl.styles import Font, PatternFill, Alignment\n",
                "from copy import copy\n",
                "import math\n",
                "import sys\n",
                "from google.colab import files\n",
                "import io\n",
                "import re\n",
                "import warnings\n",
                "warnings.filterwarnings('ignore')\n\n",
                "print('✅ All libraries loaded successfully!')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {"id": "parser", "cellView": "form"},
            "outputs": [],
            "source": [
                "#@title 🏗️ Load Complete Strongbox Parser\n\n",
                "class StrongboxParserColab:\n",
                "    def __init__(self):\n",
                "        self.source_file = None\n",
                "        self.start_date = None\n",
                "        self.end_date = None\n",
                "        self.begin_balance_date = None\n",
                "        self.source_data = {}\n",
                "        self.template_data = {}\n",
                "        self.output_filename = None\n",
                "        self.date_columns = {}\n\n",
                "    def print_and_log(self, message):\n",
                "        print(message)\n\n",
                "    def update_status(self, message, progress=None):\n",
                "        if progress:\n",
                "            print(f'[{progress:2d}%] {message}')\n",
                "        else:\n",
                "            print(message)\n\n",
                "    def determine_date_range(self):\n",
                "        self.update_status('Determining date range from TB sheet...', 10)\n",
                "        \n",
                "        date_row = pd.read_excel(self.source_file, sheet_name='TB', header=None, nrows=1, skiprows=3)\n",
                "        date_row = date_row.iloc[0]\n",
                "        \n",
                "        date_columns = {}\n",
                "        for col_idx, value in enumerate(date_row):\n",
                "            try:\n",
                "                if pd.notna(value):\n",
                "                    if isinstance(value, str):\n",
                "                        for fmt in ['%m/%d/%Y', '%Y-%m-%d', '%m-%d-%Y', '%d-%b-%Y', '%d/%b/%Y']:\n",
                "                            try:\n",
                "                                date = datetime.strptime(value, fmt)\n",
                "                                date_columns[date] = col_idx\n",
                "                                break\n",
                "                            except ValueError:\n",
                "                                continue\n",
                "                    else:\n",
                "                        date = pd.to_datetime(value)\n",
                "                        date_columns[date] = col_idx\n",
                "            except Exception:\n",
                "                continue\n",
                "        \n",
                "        if not date_columns:\n",
                "            raise Exception('No valid dates found in TB sheet row 4')\n",
                "        \n",
                "        tb_dates = sorted(date_columns.keys())\n",
                "        if len(tb_dates) < 2:\n",
                "            raise Exception('Need at least two dates in TB sheet')\n",
                "        \n",
                "        self.begin_balance_date = tb_dates[0]\n",
                "        self.start_date = tb_dates[0] + relativedelta(days=1)\n",
                "        self.end_date = tb_dates[-1]\n",
                "        self.date_columns = date_columns\n",
                "        \n",
                "        self.print_and_log(f'📅 Date range: {self.start_date.strftime(\"%Y-%m-%d\")} to {self.end_date.strftime(\"%Y-%m-%d\")}')\n",
                "        self.print_and_log(f'📅 Date columns mapping: {[(d.strftime(\"%Y-%m-%d\"), idx) for d, idx in sorted(date_columns.items())]}')\n",
                "        return date_columns\n\n",
                "    def load_source_data(self):\n",
                "        self.update_status('Loading transaction data...', 20)\n",
                "        \n",
                "        excel_file = pd.ExcelFile(self.source_file)\n",
                "        txn_sheets = [s for s in excel_file.sheet_names if s.startswith('TXN-FY')]\n",
                "        \n",
                "        self.print_and_log(f'📊 Found {len(txn_sheets)} transaction sheets: {txn_sheets}')\n",
                "        \n",
                "        for sheet_name in txn_sheets:\n",
                "            try:\n",
                "                df = pd.read_excel(self.source_file, sheet_name=sheet_name)\n",
                "                self.print_and_log(f'📋 {sheet_name}: {len(df)} rows loaded')\n",
                "                \n",
                "                # Convert date columns using the correct column names\n",
                "                for col in ['Transaction Date', 'Fiscal Month']:\n",
                "                    if col in df.columns:\n",
                "                        df[col] = pd.to_datetime(df[col], errors='coerce')\n",
                "                \n",
                "                # Convert numeric columns using the correct column names\n",
                "                for col in ['Debit', 'Credit']:\n",
                "                    if col in df.columns:\n",
                "                        df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0)\n",
                "                \n",
                "                # Filter by Fiscal Month date range (the original script uses Fiscal Month for filtering)\n",
                "                if self.start_date is not None and self.end_date is not None:\n",
                "                    if 'Fiscal Month' in df.columns:\n",
                "                        mask = (df['Fiscal Month'] >= self.begin_balance_date) & (df['Fiscal Month'] <= self.end_date)\n",
                "                        df_filtered = df[mask]\n",
                "                        self.print_and_log(f'📅 {sheet_name}: {len(df_filtered)} transactions in date range')\n",
                "                        df = df_filtered\n",
                "                \n",
                "                if not df.empty:\n",
                "                    self.source_data[sheet_name] = df\n",
                "                    self.print_and_log(f'✅ {sheet_name}: {len(df)} transactions loaded')\n",
                "                \n",
                "            except Exception as e:\n",
                "                self.print_and_log(f'⚠️ Error loading {sheet_name}: {str(e)}')\n\n",
                "    def load_trial_balance_data(self):\n",
                "        self.update_status('Loading trial balance data...', 40)\n",
                "        \n",
                "        # Get the date_columns that were determined in determine_date_range\n",
                "        date_columns = self.date_columns\n",
                "        \n",
                "        # Find the closest TB dates to our calculated range (EXACTLY like original)\n",
                "        available_tb_dates = sorted(date_columns.keys())\n",
                "        \n",
                "        # Find closest beginning date (on or before our begin_balance_date)\n",
                "        closest_begin_date = None\n",
                "        for tb_date in available_tb_dates:\n",
                "            if tb_date <= self.begin_balance_date:\n",
                "                closest_begin_date = tb_date\n",
                "            else:\n",
                "                break\n",
                "        \n",
                "        # If no TB date is on or before our begin_balance_date, use the earliest TB date\n",
                "        if closest_begin_date is None:\n",
                "            closest_begin_date = available_tb_dates[0]\n",
                "            self.print_and_log(f'WARNING: No TB date found on or before calculated begin balance date {self.begin_balance_date.strftime(\"%Y-%m-%d\")}, using earliest TB date {closest_begin_date.strftime(\"%Y-%m-%d\")}')\n",
                "        \n",
                "        # Find closest ending date (on or after our end_date)\n",
                "        closest_end_date = None\n",
                "        for tb_date in reversed(available_tb_dates):\n",
                "            if tb_date >= self.end_date:\n",
                "                closest_end_date = tb_date\n",
                "            else:\n",
                "                break\n",
                "        \n",
                "        # If no TB date is on or after our end_date, use the latest TB date\n",
                "        if closest_end_date is None:\n",
                "            closest_end_date = available_tb_dates[-1]\n",
                "            self.print_and_log(f'WARNING: No TB date found on or after calculated end date {self.end_date.strftime(\"%Y-%m-%d\")}, using latest TB date {closest_end_date.strftime(\"%Y-%m-%d\")}')\n",
                "        \n",
                "        self.print_and_log(f'Target dates:')\n",
                "        self.print_and_log(f'Begin date: {self.begin_balance_date}')\n",
                "        self.print_and_log(f'End date: {self.end_date}')\n",
                "        self.print_and_log(f'Begin balance date (exact): {closest_begin_date}')\n",
                "        self.print_and_log(f'End balance date (exact): {closest_end_date}')\n",
                "        \n",
                "        return self._extract_trial_balance_data(date_columns, closest_begin_date, closest_end_date)\n\n",
                "    def _extract_trial_balance_data(self, date_columns, closest_begin_date, closest_end_date):\n",
                "        \"\"\"Extract data from the TB sheet using openpyxl (EXACTLY like original)\"\"\"\n",
                "        try:\n",
                "            self.print_and_log('Opening workbook for trial balance data...')\n",
                "            self.update_status('Opening workbook for trial balance...', 52)\n",
                "            wb = openpyxl.load_workbook(self.source_file, data_only=True, read_only=True)\n",
                "            self.print_and_log('Workbook opened successfully')\n",
                "            \n",
                "            self.print_and_log('Accessing TB sheet...')\n",
                "            self.update_status('Accessing TB sheet...', 54)\n",
                "            tb_sheet = wb['TB']\n",
                "            self.print_and_log(f'TB sheet accessed. Sheet has {tb_sheet.max_row} rows and {tb_sheet.max_column} columns')\n",
                "            \n",
                "            # Find Financial Statement Classification Path column\n",
                "            self.print_and_log('Finding Financial Statement Classification column...')\n",
                "            self.update_status('Finding classification column...', 56)\n",
                "            fin_statement_col = self._find_financial_classification_column(tb_sheet)\n",
                "            \n",
                "            # Print column indices for debugging\n",
                "            self.print_and_log(f'Column indices:')\n",
                "            self.print_and_log(f'Begin date column index: {date_columns[closest_begin_date]}')\n",
                "            self.print_and_log(f'End date column index: {date_columns[closest_end_date]}')\n",
                "            self.print_and_log(f'Financial Statement Classification column index: {fin_statement_col}')\n",
                "            \n",
                "            self.print_and_log('Starting to extract data from TB sheet...')\n",
                "            self.update_status('Extracting TB data...', 58)\n",
                "            \n",
                "            data = []\n",
                "            rows_processed = 0\n",
                "            \n",
                "            # Process rows starting from row 5 (like original)\n",
                "            for row_idx in range(5, tb_sheet.max_row + 1):\n",
                "                rows_processed += 1\n",
                "                \n",
                "                try:\n",
                "                    account_id = tb_sheet.cell(row=row_idx, column=4).value\n",
                "                    if account_id is not None:\n",
                "                        account_id = str(account_id).strip()\n",
                "                        # Only skip rows with exact header matches, not all rows containing 'account'\n",
                "                        if account_id.lower() == 'account id' or account_id.lower() == 'account':\n",
                "                            if rows_processed <= 20:  # Only print for first 20 rows to avoid spam\n",
                "                                self.print_and_log(f'Skipping header row {row_idx} with account_id: {account_id}')\n",
                "                            continue\n",
                "                            \n",
                "                        account_name = tb_sheet.cell(row=row_idx, column=6).value\n",
                "                        begin_cell = tb_sheet.cell(row=row_idx, column=date_columns[closest_begin_date] + 1)\n",
                "                        end_cell = tb_sheet.cell(row=row_idx, column=date_columns[closest_end_date] + 1)\n",
                "                        \n",
                "                        # Get Financial Statement Classification using the identified column\n",
                "                        fin_statement_class = tb_sheet.cell(row=row_idx, column=fin_statement_col).value\n",
                "                        \n",
                "                        # Debug output for Financial Statement Classification for the first few rows\n",
                "                        if row_idx < 12:\n",
                "                            self.print_and_log(f'Row {row_idx}, Account: {account_id}, Begin: {begin_cell.value}, End: {end_cell.value}, FS Classification (Column {fin_statement_col}): {fin_statement_class}')\n",
                "                        \n",
                "                        # Handle different types appropriately\n",
                "                        if fin_statement_class is None:\n",
                "                            fin_statement_class = ''\n",
                "                        else:\n",
                "                            fin_statement_class = str(fin_statement_class).strip()\n",
                "                        \n",
                "                        try:\n",
                "                            begin_balance = float(begin_cell.value) if begin_cell.value is not None else 0.0\n",
                "                        except (ValueError, TypeError):\n",
                "                            begin_balance = 0.0\n",
                "                            \n",
                "                        try:\n",
                "                            end_balance = float(end_cell.value) if end_cell.value is not None else 0.0\n",
                "                        except (ValueError, TypeError):\n",
                "                            end_balance = 0.0\n",
                "                        \n",
                "                        data.append({\n",
                "                            'Account Id': account_id,\n",
                "                            'Account Name': str(account_name).strip() if account_name is not None else '',\n",
                "                            'Beginning Balance': begin_balance,\n",
                "                            'Ending Balance': end_balance,\n",
                "                            'Financial Statement Classification': fin_statement_class\n",
                "                        })\n",
                "                except Exception as e:\n",
                "                    if rows_processed <= 20:  # Only print errors for first 20 rows to avoid spam\n",
                "                        self.print_and_log(f'Error processing TB sheet row {row_idx}: {str(e)}. Skipping row.')\n",
                "                    continue\n",
                "            \n",
                "            self.print_and_log(f'Completed processing {rows_processed} rows from TB sheet')\n",
                "            self.print_and_log(f'Extracted {len(data)} valid account records')\n",
                "            self.update_status('Converting TB data to DataFrame...', 68)\n",
                "            \n",
                "            # Convert to DataFrame\n",
                "            tb_data = pd.DataFrame(data)\n",
                "            self.print_and_log('First few rows of TB data:')\n",
                "            if len(tb_data) > 0:\n",
                "                self.print_and_log(tb_data.head().to_string())\n",
                "            else:\n",
                "                self.print_and_log('No data extracted!')\n",
                "            \n",
                "            return tb_data\n",
                "            \n",
                "        except Exception as e:\n",
                "            self.print_and_log(f'Error in _extract_trial_balance_data: {str(e)}')\n",
                "            raise\n",
                "        finally:\n",
                "            # Close the workbook if it exists\n",
                "            try:\n",
                "                if 'wb' in locals():\n",
                "                    wb.close()\n",
                "                    self.print_and_log('Workbook closed')\n",
                "            except:\n",
                "                pass\n\n",
                "    def _find_financial_classification_column(self, tb_sheet):\n",
                "        \"\"\"Find the Financial Statement Classification column in the TB sheet (EXACTLY like original)\"\"\"\n",
                "        self.print_and_log('Searching for Financial Statement Classification column...')\n",
                "        fin_statement_col = None\n",
                "        \n",
                "        # Search more efficiently - check fewer rows and columns first\n",
                "        for row_idx in range(1, 6):  # Check first 5 rows for headers\n",
                "            self.print_and_log(f'Checking row {row_idx} for headers...')\n",
                "            for col_idx in range(1, 15):  # Check first 14 columns (reduced from 25)\n",
                "                try:\n",
                "                    cell_value = tb_sheet.cell(row=row_idx, column=col_idx).value\n",
                "                    if cell_value:\n",
                "                        cell_text = str(cell_value).lower()\n",
                "                        if 'financial statement classification' in cell_text or 'fin statement classification' in cell_text:\n",
                "                            fin_statement_col = col_idx\n",
                "                            self.print_and_log(f'Found Financial Statement Classification header in row {row_idx}, column {col_idx}: {cell_value}')\n",
                "                            return fin_statement_col\n",
                "                except Exception as e:\n",
                "                    # Silently continue if there's an error reading a cell\n",
                "                    continue\n",
                "            if fin_statement_col:\n",
                "                break\n",
                "        \n",
                "        if not fin_statement_col:\n",
                "            # Default to column C (3) as specified in original\n",
                "            fin_statement_col = 3\n",
                "            self.print_and_log(f'No Financial Statement Classification header found, using default column C (3)')\n",
                "        \n",
                "        return fin_statement_col\n\n",
                "    def determine_account_type(self, fs_classification):\n",
                "        \"\"\"Determine Account Type based on Financial Statement Classification Path (EXACTLY like original)\"\"\"\n",
                "        if pd.isna(fs_classification) or fs_classification == '':\n",
                "            return ''\n",
                "            \n",
                "        fs_classification = str(fs_classification).strip()\n",
                "        \n",
                "        if fs_classification.startswith('Total Assets'):\n",
                "            return 'Assets'\n",
                "        elif fs_classification.startswith('Total Liabilities and Equity → Total Liabilities'):\n",
                "            return 'Liabilities'\n",
                "        elif fs_classification.startswith('Total Liabilities and Equity → Total Equity'):\n",
                "            return 'Equity'\n",
                "        elif fs_classification.startswith('Net Income → Operating Profit → Gross Profit → Total Net Sales'):\n",
                "            return 'Income'\n",
                "        elif fs_classification.startswith('Net Income → Operating Profit → Gross Profit → Total COGS/COS'):\n",
                "            return 'Expense'\n",
                "        elif fs_classification.startswith('Net Income → Operating Profit → Total Operating Expenses'):\n",
                "            return 'Expense'\n",
                "        else:\n",
                "            return ''\n\n",
                "    def create_trial_balance(self):\n",
                "        \"\"\"Create Comparative Trial Balances tab (matches original output format)\"\"\"\n",
                "        self.update_status('Creating trial balance...', 70)\n",
                "        tb_data = self.source_data['TB']\n",
                "        \n",
                "        # Filter out header rows (matches original logic)\n",
                "        tb_data = tb_data[~((tb_data['Account Id'].str.lower() == 'account id') | \n",
                "                           (tb_data['Account Id'].str.lower() == 'account'))]\n",
                "        \n",
                "        # Create DataFrame with exact column names from original\n",
                "        trial_balance = pd.DataFrame({\n",
                "            'Account ID': tb_data['Account Id'],\n",
                "            'Account Name': tb_data['Account Name'],\n",
                "            'Beginning Balance \\n(Prior Period Balance)': tb_data['Beginning Balance'],\n",
                "            'Ending Balance': tb_data['Ending Balance'],\n",
                "            'Account Type \\n(see Mapping Categories tab)': '',\n",
                "            'Account Mapping \\n(see Mapping Categories tab)': '',\n",
                "            'Account Description': tb_data['Financial Statement Classification']\n",
                "        })\n",
                "        \n",
                "        # Apply account type classification\n",
                "        trial_balance['Account Type \\n(see Mapping Categories tab)'] = trial_balance['Account Description'].apply(self.determine_account_type)\n",
                "        \n",
                "        # Debug: show sample of trial balance\n",
                "        self.print_and_log(f'Trial Balance sample columns: {trial_balance.columns.tolist()}')\n",
                "        if len(trial_balance) > 0:\n",
                "            self.print_and_log(f'Sample TB row: {trial_balance.iloc[0].to_dict()}')\n",
                "        \n",
                "        # Remove rows with empty Account IDs\n",
                "        trial_balance = trial_balance[trial_balance['Account ID'].notna() & (trial_balance['Account ID'] != '')]\n",
                "        trial_balance = trial_balance.reset_index(drop=True)\n",
                "        \n",
                "        self.print_and_log(f'✅ Trial balance created: {len(trial_balance)} accounts')\n",
                "        return trial_balance\n\n",
                "    def create_journal_entries(self):\n",
                "        \"\"\"Create Journal Entries & Lines tab (matches original output format)\"\"\"\n",
                "        self.update_status('Creating journal entries...', 60)\n",
                "        \n",
                "        # Get transaction sheets\n",
                "        transaction_sheets = {k: v for k, v in self.source_data.items() if k.startswith('TXN-FY')}\n",
                "        self.print_and_log(f'Found sheets: {list(transaction_sheets.keys())}')\n",
                "        \n",
                "        processed_sheets = []\n",
                "        for sheet_name, df in transaction_sheets.items():\n",
                "            try:\n",
                "                self.print_and_log(f'Processing sheet: {sheet_name}')\n",
                "                df_copy = df.copy()\n",
                "                \n",
                "                # Convert columns to appropriate types (using original column names)\n",
                "                df_copy['Transaction Id'] = df_copy['Transaction Id'].astype(str)\n",
                "                df_copy['Memo'] = df_copy['Memo'].fillna('')\n",
                "                df_copy['Doc/Ref No'] = df_copy['Doc/Ref No'].fillna('')\n",
                "                df_copy['Account Id'] = df_copy['Account Id'].astype(str)\n",
                "                \n",
                "                # Convert numeric columns\n",
                "                df_copy['Debit'] = pd.to_numeric(df_copy['Debit'], errors='coerce').fillna(0)\n",
                "                df_copy['Credit'] = pd.to_numeric(df_copy['Credit'], errors='coerce').fillna(0)\n",
                "                \n",
                "                # Create the required columns with exact names from original\n",
                "                processed_df = pd.DataFrame({\n",
                "                    'Journal ID': df_copy['Transaction Id'],\n",
                "                    'Journal Entry Description': df_copy['Doc/Ref No'],\n",
                "                    'Posted Date': df_copy['Transaction Date'],\n",
                "                    'Account ID': df_copy['Account Id'],\n",
                "                    'Journal Line Description': df_copy['Memo'],\n",
                "                    'Debit Amount': df_copy['Debit'],\n",
                "                    'Credit Amount': df_copy['Credit']\n",
                "                })\n",
                "                \n",
                "                processed_sheets.append(processed_df)\n",
                "                self.print_and_log(f'Successfully processed sheet: {sheet_name}')\n",
                "                \n",
                "            except Exception as e:\n",
                "                self.print_and_log(f'Error processing sheet {sheet_name}: {str(e)}')\n",
                "                continue\n",
                "        \n",
                "        # Combine all processed sheets\n",
                "        if not processed_sheets:\n",
                "            raise Exception('No sheets were successfully processed')\n",
                "        \n",
                "        journal_entries = pd.concat(processed_sheets, ignore_index=True)\n",
                "        self.print_and_log(f'✅ Journal entries created: {len(journal_entries)} entries')\n",
                "        return journal_entries\n\n",
                "    def create_other_sheets(self, workbook, styles):\n",
                "        \"\"\"Create and format all other required sheets\"\"\"\n",
                "        self.print_and_log('Creating additional required sheets...')\n",
                "        \n",
                "        # Create Instructions sheet\n",
                "        instructions_sheet = workbook.create_sheet('Instructions')\n",
                "        instructions_sheet.append(['Strongbox Parser Instructions'])\n",
                "        instructions_sheet.append(['This file was processed by Strongbox Parser for Audit Sight import.'])\n",
                "        instructions_sheet.append([''])\n",
                "        instructions_sheet.append(['Main Tabs:'])\n",
                "        instructions_sheet.append(['- Comparative Trial Balances: Account balances and classifications'])\n",
                "        instructions_sheet.append(['- Journal Entries & Lines: All transaction detail'])\n",
                "        instructions_sheet.append(['- Banking Accts: Banking account setup (if applicable)'])\n",
                "        instructions_sheet.append(['- Banking Txn: Banking transactions (if applicable)'])\n",
                "        \n",
                "        # Create Data Validation Tests sheet\n",
                "        validation_sheet = workbook.create_sheet('Data Validation Tests')\n",
                "        validation_sheet.append(['Data Validation Tests'])\n",
                "        validation_sheet.append(['This sheet can be used for data validation checks.'])\n",
                "        \n",
                "        # Create Notes sheet\n",
                "        notes_sheet = workbook.create_sheet('Notes')\n",
                "        notes_sheet.append(['Notes and Comments'])\n",
                "        notes_sheet.append(['Add any notes about this import here.'])\n",
                "        \n",
                "        # Create Banking Accts sheet with specific formatting\n",
                "        banking_accts_sheet = workbook.create_sheet('Banking Accts')\n",
                "        \n",
                "        # Add headers for Banking Accts\n",
                "        banking_accts_sheet.append(['Required', 'Required', 'Optional', 'Optional'])\n",
                "        banking_accts_sheet.append(['Account Number', 'Account Name', 'Institution', 'Currency'])\n",
                "        \n",
                "        # Style row 1 headers for Banking Accts\n",
                "        for col in range(1, 3):  # Columns A-B (Required)\n",
                "            cell = banking_accts_sheet.cell(row=1, column=col)\n",
                "            cell.font = styles['header_font']\n",
                "            cell.fill = styles['blue_fill']\n",
                "            cell.alignment = styles['center_alignment']\n",
                "        \n",
                "        for col in range(3, 5):  # Columns C-D (Optional)\n",
                "            cell = banking_accts_sheet.cell(row=1, column=col)\n",
                "            cell.font = styles['header_font']\n",
                "            cell.fill = styles['gray_fill']\n",
                "            cell.alignment = styles['center_alignment']\n",
                "        \n",
                "        # Style row 2 headers for Banking Accts\n",
                "        for col in range(1, 5):  # All columns A-D\n",
                "            cell = banking_accts_sheet.cell(row=2, column=col)\n",
                "            cell.font = styles['header_font']\n",
                "            cell.fill = styles['dark_blue_fill']\n",
                "            cell.alignment = styles['center_alignment']\n",
                "        \n",
                "        # Create Banking Txn sheet with specific formatting\n",
                "        banking_txn_sheet = workbook.create_sheet('Banking Txn')\n",
                "        \n",
                "        # Add headers for Banking Txn\n",
                "        banking_txn_sheet.append(['Required', 'Required', 'Required', 'Required'])\n",
                "        banking_txn_sheet.append(['Posted Date', 'Description', 'Amount', 'Account Number'])\n",
                "        \n",
                "        # Style row 1 headers for Banking Txn (all Required)\n",
                "        for col in range(1, 5):  # Columns A-D (all Required)\n",
                "            cell = banking_txn_sheet.cell(row=1, column=col)\n",
                "            cell.font = styles['header_font']\n",
                "            cell.fill = styles['blue_fill']\n",
                "            cell.alignment = styles['center_alignment']\n",
                "        \n",
                "        # Style row 2 headers for Banking Txn\n",
                "        for col in range(1, 5):  # All columns A-D\n",
                "            cell = banking_txn_sheet.cell(row=2, column=col)\n",
                "            cell.font = styles['header_font']\n",
                "            cell.fill = styles['dark_blue_fill']\n",
                "            cell.alignment = styles['center_alignment']\n",
                "        \n",
                "        # Create Mapping Categories sheet\n",
                "        mapping_sheet = workbook.create_sheet('Mapping Categories')\n",
                "        mapping_sheet.append(['Account Type Mapping Categories'])\n",
                "        mapping_sheet.append([''])\n",
                "        mapping_sheet.append(['Valid Account Types:'])\n",
                "        mapping_sheet.append(['Asset'])\n",
                "        mapping_sheet.append(['Liability'])\n",
                "        mapping_sheet.append(['Equity'])\n",
                "        mapping_sheet.append(['Revenue'])\n",
                "        mapping_sheet.append(['Expense'])\n\n",
                "    def create_output_file(self, trial_balance, journal_entries):\n",
                "        \"\"\"Create Excel output file with professional formatting (matches original)\"\"\"\n",
                "        self.update_status('Creating Excel output...', 80)\n",
                "        \n",
                "        start_str = self.start_date.strftime('%Y%m%d')\n",
                "        end_str = self.end_date.strftime('%Y%m%d')\n",
                "        self.output_filename = f'Processed_Strongbox_{start_str}_{end_str}.xlsx'\n",
                "        \n",
                "        workbook = openpyxl.Workbook()\n",
                "        \n",
                "        # Remove default sheet\n",
                "        if 'Sheet' in workbook.sheetnames:\n",
                "            workbook.remove(workbook['Sheet'])\n",
                "        \n",
                "        # Create styles (matches original)\n",
                "        header_font = Font(name='Arial', size=12, bold=True, color='FFFFFF')\n",
                "        blue_fill = PatternFill(start_color='0070C0', end_color='0070C0', fill_type='solid')\n",
                "        gray_fill = PatternFill(start_color='999999', end_color='999999', fill_type='solid')\n",
                "        dark_blue_fill = PatternFill(start_color='002060', end_color='002060', fill_type='solid')\n",
                "        center_alignment = Alignment(horizontal='center', vertical='center')\n",
                "        \n",
                "        styles = {\n",
                "            'header_font': header_font,\n",
                "            'blue_fill': blue_fill,\n",
                "            'gray_fill': gray_fill,\n",
                "            'dark_blue_fill': dark_blue_fill,\n",
                "            'center_alignment': center_alignment\n",
                "        }\n",
                "        \n",
                "        # Create Trial Balance sheet FIRST\n",
                "        tb_sheet = workbook.create_sheet('Comparative Trial Balances')\n",
                "        \n",
                "        # Set column widths for trial balance\n",
                "        tb_sheet.column_dimensions['A'].width = 17.9\n",
                "        tb_sheet.column_dimensions['B'].width = 40.0\n",
                "        tb_sheet.column_dimensions['C'].width = 20.0\n",
                "        tb_sheet.column_dimensions['D'].width = 15.7\n",
                "        tb_sheet.column_dimensions['E'].width = 20.0\n",
                "        tb_sheet.column_dimensions['F'].width = 35.7\n",
                "        tb_sheet.column_dimensions['G'].width = 25.7\n",
                "        \n",
                "        # Write trial balance headers and data\n",
                "        tb_headers = list(trial_balance.columns)\n",
                "        for col_idx, header in enumerate(tb_headers, 1):\n",
                "            cell = tb_sheet.cell(row=1, column=col_idx, value=header)\n",
                "            cell.font = header_font\n",
                "            cell.fill = dark_blue_fill\n",
                "            cell.alignment = center_alignment\n",
                "        \n",
                "        # Write trial balance data\n",
                "        for row_idx, (_, row) in enumerate(trial_balance.iterrows(), 2):\n",
                "            for col_idx, value in enumerate(row, 1):\n",
                "                tb_sheet.cell(row=row_idx, column=col_idx, value=value)\n",
                "        \n",
                "        # Create Journal Entries sheet SECOND\n",
                "        je_sheet = workbook.create_sheet('Journal Entries & Lines')\n",
                "        \n",
                "        # Set column widths for journal entries\n",
                "        je_sheet.column_dimensions['A'].width = 14.3\n",
                "        je_sheet.column_dimensions['B'].width = 48.6\n",
                "        je_sheet.column_dimensions['C'].width = 15.7\n",
                "        je_sheet.column_dimensions['D'].width = 20.0\n",
                "        je_sheet.column_dimensions['E'].width = 35.7\n",
                "        je_sheet.column_dimensions['F'].width = 15.7\n",
                "        je_sheet.column_dimensions['G'].width = 15.7\n",
                "        \n",
                "        # Write journal entries headers with Required/Optional row\n",
                "        je_sheet.append(['Required', 'Optional', 'Required', 'Required', 'Optional', 'Required', 'Required'])\n",
                "        je_sheet.append(list(journal_entries.columns))\n",
                "        \n",
                "        # Style headers\n",
                "        required_cols = [1, 3, 4, 6, 7]\n",
                "        optional_cols = [2, 5]\n",
                "        \n",
                "        for col in required_cols:\n",
                "            cell = je_sheet.cell(row=1, column=col)\n",
                "            cell.font = header_font\n",
                "            cell.fill = blue_fill\n",
                "            cell.alignment = center_alignment\n",
                "        \n",
                "        for col in optional_cols:\n",
                "            cell = je_sheet.cell(row=1, column=col)\n",
                "            cell.font = header_font\n",
                "            cell.fill = gray_fill\n",
                "            cell.alignment = center_alignment\n",
                "        \n",
                "        # Style column name headers\n",
                "        for col in range(1, 8):\n",
                "            cell = je_sheet.cell(row=2, column=col)\n",
                "            cell.font = header_font\n",
                "            cell.fill = dark_blue_fill\n",
                "            cell.alignment = center_alignment\n",
                "        \n",
                "        # Write journal entries data\n",
                "        for row_idx, (_, row) in enumerate(journal_entries.iterrows(), 3):\n",
                "            for col_idx, value in enumerate(row, 1):\n",
                "                cell = je_sheet.cell(row=row_idx, column=col_idx, value=value)\n",
                "                # Apply date formatting to Posted Date column\n",
                "                if col_idx == 3:  # Posted Date column\n",
                "                    cell.number_format = 'M/D/YYYY'\n",
                "        \n",
                "        # Create all other required sheets AFTER main data sheets\n",
                "        self.create_other_sheets(workbook, styles)\n",
                "        \n",
                "        workbook.save(self.output_filename)\n",
                "        workbook.close()\n",
                "        \n",
                "        self.print_and_log(f'✅ Output file created: {self.output_filename}')\n",
                "        return self.output_filename\n\n",
                "    def run(self):\n",
                "        try:\n",
                "            self.print_and_log('🚀 Starting Strongbox Parser...')\n",
                "            \n",
                "            # First determine date range from TB sheet\n",
                "            self.determine_date_range()\n",
                "            \n",
                "            # Then load transaction data with date filtering\n",
                "            self.load_source_data()\n",
                "            \n",
                "            # Load trial balance data using openpyxl (like original)\n",
                "            tb_data = self.load_trial_balance_data()\n",
                "            self.source_data['TB'] = tb_data\n",
                "            \n",
                "            # Create outputs from real data\n",
                "            trial_balance = self.create_trial_balance()\n",
                "            journal_entries = self.create_journal_entries()\n",
                "            \n",
                "            # Create output file\n",
                "            output_file = self.create_output_file(trial_balance, journal_entries)\n",
                "            \n",
                "            self.update_status('Processing complete!', 100)\n",
                "            self.print_and_log('\\n🎉 SUCCESS! Processing completed!')\n",
                "            \n",
                "            return output_file\n",
                "            \n",
                "        except Exception as e:\n",
                "            self.print_and_log(f'\\n❌ Error: {str(e)}')\n",
                "            raise\n\n",
                "print('✅ Complete Strongbox Parser loaded and ready!')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {"id": "upload", "cellView": "form"},
            "outputs": [],
            "source": [
                "#@title 📁 Upload Your Strongbox Excel File\n\n",
                "print('📁 UPLOAD YOUR STRONGBOX EXCEL FILE')\n",
                "print('=' * 40)\n",
                "print('Requirements:')\n",
                "print('  ✓ Excel file (.xlsx format)')\n",
                "print('  ✓ TB sheet with trial balance data')\n",
                "print('  ✓ TXN-FY sheets with transactions')\n",
                "print('  ✓ Dates in row 4 of TB sheet')\n",
                "print()\n",
                "print('Click Choose Files below and select your file:')\n\n",
                "uploaded = files.upload()\n\n",
                "if uploaded:\n",
                "    source_filename = list(uploaded.keys())[0]\n",
                "    file_size = len(uploaded[source_filename])\n",
                "    print(f'\\n✅ SUCCESS! File uploaded:')\n",
                "    print(f'   📄 Name: {source_filename}')\n",
                "    print(f'   📊 Size: {file_size:,} bytes ({file_size/1024/1024:.1f} MB)')\n",
                "    print(f'\\n🔄 Ready to process! Run the next cell.')\n",
                "else:\n",
                "    print('\\n❌ No file uploaded. Please try again.')\n",
                "    source_filename = None"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {"id": "process", "cellView": "form"},
            "outputs": [],
            "source": [
                "#@title 🔄 Process Your File\n\n",
                "if 'source_filename' in globals() and source_filename:\n",
                "    print('🔄 PROCESSING YOUR STRONGBOX FILE')\n",
                "    print('=' * 35)\n",
                "    print(f'File: {source_filename}')\n",
                "    print()\n",
                "    \n",
                "    # Initialize and run parser\n",
                "    parser = StrongboxParserColab()\n",
                "    parser.source_file = source_filename\n",
                "    \n",
                "    try:\n",
                "        output_file = parser.run()\n",
                "        \n",
                "        print('\\n' + '=' * 50)\n",
                "        print('🎉 SUCCESS! YOUR FILE HAS BEEN PROCESSED!')\n",
                "        print('=' * 50)\n",
                "        print(f'✅ Output file: {output_file}')\n",
                "        print('\\n📋 Your file contains:')\n",
                "        print('   📊 Comparative Trial Balances (Your Real Data)')\n",
                "        print('   📝 Journal Entries & Lines (Your Real Transactions)')\n",
                "        print('   📋 Instructions, Banking Accts, Banking Txn, etc.')\n",
                "        print('   🎨 Professional formatting')\n",
                "        print('   🧹 Data cleaning applied')\n",
                "        print('\\n📥 Ready for download! Run the next cell.')\n",
                "        \n",
                "    except Exception as e:\n",
                "        print('\\n' + '=' * 40)\n",
                "        print('❌ PROCESSING ERROR')\n",
                "        print('=' * 40)\n",
                "        print(f'Error: {str(e)}')\n",
                "        print('\\n🔍 Please check:')\n",
                "        print('  • File has TB sheet with trial balance')\n",
                "        print('  • TB sheet has dates in row 4')\n",
                "        print('  • File has TXN-FY sheets with transactions')\n",
                "        print('  • File is not password protected')\n",
                "        print('  • File format is .xlsx (not .xls)')\n",
                "        output_file = None\n",
                "        \n",
                "else:\n",
                "    print('⚠️ Please upload a file first by running the cell above.')\n",
                "    output_file = None"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {"id": "download", "cellView": "form"},
            "outputs": [],
            "source": [
                "#@title 📥 Download Your Processed File\n\n",
                "if 'output_file' in globals() and output_file:\n",
                "    print('📥 DOWNLOADING YOUR PROCESSED FILE')\n",
                "    print('=' * 38)\n",
                "    print(f'File: {output_file}')\n",
                "    print('\\nThe file will download to your browser\\'s Downloads folder.')\n",
                "    print()\n",
                "    \n",
                "    # Check if file exists before downloading\n",
                "    import os\n",
                "    if os.path.exists(output_file):\n",
                "        # Download the file\n",
                "        files.download(output_file)\n",
                "        \n",
                "        print('✅ Download started!')\n",
                "        print('\\n🎉 ALL DONE!')\n",
                "        print('=' * 15)\n",
                "        print('Your Audit Sight formatted file is ready!')\n",
                "        print('\\n💡 What you got:')\n",
                "        print('  • Complete trial balance from your TB sheet')\n",
                "        print('  • All journal entries from your TXN-FY sheets')\n",
                "        print('  • Proper date filtering and account classification')\n",
                "        print('  • Unicode cleaning and data validation')\n",
                "        print('  • Professional Excel formatting')\n",
                "        print('  • All required tabs for Audit Sight import')\n",
                "        print('\\n📊 Ready for Audit Sight import!')\n",
                "    else:\n",
                "        print('❌ Error: Output file not found!')\n",
                "        print(f'Expected file: {output_file}')\n",
                "    \n",
                "else:\n",
                "    print('⚠️ No file ready for download.')\n",
                "    print('Please upload and process a file first.')"
            ]
        }
    ],
    "metadata": {
        "colab": {
            "provenance": [],
            "collapsed_sections": ["setup", "imports", "parser"],
            "name": "Strongbox Parser - Complete Edition"
        },
        "kernelspec": {
            "display_name": "Python 3",
            "name": "python3"
        },
        "language_info": {
            "name": "python"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 0
}

# Save the notebook
with open('Strongbox_Parser_Complete.ipynb', 'w') as f:
    json.dump(notebook, f, indent=2)

print("✅ Complete notebook created successfully: Strongbox_Parser_Complete.ipynb") 